### ISSUE TITLE
libserialport podspec help

### ISSUE THREAD

**Issue by vladvoina** [jpnurmi/flutter_serial_port#5]
Hey JP - not really an issue, just reaching for help. 

Been using your plugin as a guide to building my own (c++ based) plugin (also read your article on medium), but I can't figure out how you bundled libserialport as a .framework. In short, I can't find the .podspec of libserialport (which you use as a dependency in the macos podspec). I can't find it in the Cocoapods Master Repo either.

Help would be much appreciated!

**Comment by jpnurmi** [comment]
Hi, the podspec file is in the "podspec" branch of my libserialport fork: https://github.com/jpnurmi/libserialport/commit/7472c25e9eebb153539a5c0e9165df4afa7c3611 and the published pod is available at https://cocoapods.org/pods/libserialport
