### ISSUE TITLE
maximum byte to send

### ISSUE THREAD

**Issue by YoussefBadal** [jpnurmi/flutter_serial_port#7]
i don't know if that is issue or configuration error, but the maximum number of bytes to send is limited by 80 bytes. how we can send more than 80 bytes?

**Comment by jpnurmi** [comment]
Hi, on which platform? Would it help to call `SerialPort.drain()` if it's an option to wait in between?

**Comment by YoussefBadal** [comment]
Hi, I tested it on windows,  as workaround i add some delay between 80 bytes package. That work but I'm  asking if there is some low level configuration to change it ?

**Comment by jpnurmi** [comment]
Not to my knowledge, but what about a blocking write?
```
sp.write(bytes, {timeout: 0});
```

**Comment by YoussefBadal** [comment]
I tried also the blocking write.   i keep the workaround .Thanks for your help.
