### ISSUE TITLE
nullsafety with ffi1.0.0

### ISSUE THREAD

**Issue by Coimbra1984** [jpnurmi/flutter_serial_port#9]
Hi,

I just saw that dart_serial_port has already nullsafety and ffi1.0.0 dependency. Can you integrate that upgrade here also? I'd like to upgrade my application to flutter 2.

**Comment by jpnurmi** [comment]
Hi, thanks for the reminder. I pushed a pre-release for now: https://github.com/jpnurmi/flutter_serial_port/commit/ce31076cd56fcb489354fcb3c0eba26798619ea7 (until a stable version of dart_serial_port is out)
